apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-showcase-demo
  labels: 
    component: backstage-workloads
  annotations:
    argocd/app-name: 'guestbook'
    # github.com/project-slug: janus-idp/backstage-showcase
    quay.io/repository-slug: janus-idp/backstage-showcase
    backstage.io/kubernetes-id: test-backstage
    # janus-idp.io/tekton-enabled: 'true'
    janus-idp.io/tekton: test-backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  system: system:default/janus-idp
  owner: user:default/invinciblejai
